### PR TITLE
Lep-457 delete legacy check

### PR DESCRIPTION
**Pull request by starswan**
## What does this pull request do?

Remove CLA's (legacy) eligibility checker and associated code.

This is the clean-up, following the [CFE-integration](https://github.com/ministryofjustice/cla_backend/pull/1082/files), which is now merged and released.

## Checklist

- [x] Provided JIRA ticket number in the title, e.g. "LGA-152: Sample title"

### CODE REVIEW

**Comment by davidread** [comment]
_is_non_means_tested() is not called anywhere

**Review by davidread — APPROVED** [review]

**Comment by davidread** [comment]
Otherwise fine.

Added label to remind not to merge until cfe-integration is merged & deployed

**Comment by davidread** [comment]
`@log_only_critical` can be removed too - it’s only to suppress log.error when comparing cfe result with legacy_check()

**Review by psweeting1 — DISMISSED** [review]
LGTM

**Review by Pheonnexx — DISMISSED** [review]
LGTM

**Review by BenMillar-CGI — APPROVED** [review]
Looks good to me, thank you very much 👍

**Review by Pheonnexx — APPROVED** [review]

**Review by TawneeOwl — APPROVED** [review]
LGTM

**Pull request merged**
