### PR TITLE
LGA-1774 - Django rest framework upgrade from 3.0.5 to 3.1.3

### PR DESCRIPTION
**Pull request by said-moj**
## What does this pull request do?

- Upgraded Django rest framework package to from 3.0.5 to 3.1.3
- Replace deprecated 3.0 request.DATA in favour of request.data
- Replace deprecated 3.0 request. QUERY_PARAMS in favour of request. query_params
- Replace deprecated 3.0 request. FILES in favour of request.data
- Started using rest_framework.pagination.PageNumberPagination instead of custom core.drf.pagination.RelativeUrlPaginationSerializer pagination class

## Any other changes that would benefit highlighting?

The way pagination works has changed in 3.1. They have introduced a new pagination api in this version and expect whatever paginator you use to implement this API which wasn't possible when inheriting from django.core.paginator.Paginator.

The new API is a a wrapper for django.core.paginator.Paginator however you don't interact with it directly instead you provide implementation for things such as getting the page size(self.get_page_size)

Removed the entire cla_backend/apps/core/drf/pagination.py file because RelativeUrlPaginationSerializer was only being used to add custom previous and next links to the paginator. This is now the default behaviour of rest_framework.pagination.PageNumberPagination.get_next_link/get_previous_link

Blocked by https://github.com/ministryofjustice/cla_backend/pull/894

## Checklist

- [x] Provided JIRA ticket number in the title, e.g. "LGA-152: Sample title"

### CODE REVIEW

**Review by jogilder — DISMISSED** [review]
Your changes look good to me, what about the semgrep issues around passwords and .extra? Do we need to address those?

**Comment by said-moj** [comment]
> Your changes look good to me, what about the semgrep issues around passwords and .extra? Do we need to address those?

We pass hard-coded arguments to .extra and mostly to add hard-coded(non-user input) sql to the query
The password warning is really related to django 3 as the 1.7 we use doesn't seem to have wrapper password validation methods

**Review by Pheonnexx — APPROVED** [review]
LGTM

**Review by psweeting1 — APPROVED** [review]
LGTM

**Comment by said-moj** [comment]
> Your changes look good to me, what about the semgrep issues around passwords and .extra? Do we need to address those?

Good spot @jogilder 
I have now removed the entire cla_backend/apps/core/drf/pagination.py file because RelativeUrlPaginationSerializer was only being used to add custom previous and next links to the paginator.
This is now the default behaviour of rest_framework.pagination.PageNumberPagination.get_next_link/get_previous_link

**Comment by jogilder** [comment]
> > Your changes look good to me, what about the semgrep issues around passwords and .extra? Do we need to address those?
> 
> Good spot @jogilder I have now removed the entire cla_backend/apps/core/drf/pagination.py file because RelativeUrlPaginationSerializer was only being used to add custom previous and next links to the paginator. This is now the default behaviour of rest_framework.pagination.PageNumberPagination.get_next_link/get_previous_link

Looks good to me.

**Review by psweeting1 — APPROVED** [review]
LGTM

**Review by Pheonnexx — APPROVED** [review]

**Pull request merged**
