### PR TITLE
LGA-2590 - Skip financial assessment for under eighteens

### PR DESCRIPTION
**Pull request by said-moj**
## What does this pull request do?

Skip financial assessment for under eighteens

## Any other changes that would benefit highlighting?

Intentionally left blank.

## Checklist

- [x] Provided JIRA ticket number in the title, e.g. "LGA-152: Sample title"

### CODE REVIEW

**Review by jogilder — APPROVED** [review]
Don't like "is_you_under_18" but can live with it as it mirrors elsewhere :)

LGTM ✅

**Review by psweeting1 — DISMISSED** [review]
LGTM

**Review by jogilder — DISMISSED** [review]
LGTM

**Review by TawneeOwl — APPROVED** [review]
LGTM

**Review by jogilder — APPROVED** [review]
LGTM

**Pull request merged**
