### PR TITLE
LGA 3003: Callback capping

### PR DESCRIPTION
**Pull request by BenMillar-CGI**
##### This model consists of:
- The date of the callback, as a `DateField`.
- The time of the callback as a `CharField` with choices determined by `CALLBACK_TIME_SLOTS`.
- The capacity of the callback slot, as an `IntegerField`.

> [!TIP]
> The remaining slot capacity can be calculated by reading `CallbackTimeSlot.remaining_capacity`.

<details><summary><h3>UI Screenshot</h3></summary>
Screenshot 2024-03-17 at 21 29 47
</details>

## Adds a new CSV Uploader
The accepted CSV format is `date, time, capacity` where:
- date is of the format `dd/mm/yyyy`.
- time is of the format `hhmm`.
- capacity is a positive integer.

The CSV Uploader validates each row and returns errors where the uploaded file does not match the required format.
<details><summary><h3>UI Screenshot</h3></summary>
Screenshot 2024-03-17 at 21 51 58
</details>

## Adds a new API for populating cla_public
This can be accessed at `/checker/api/v1/callback_time_slots/`
The API will return a JSON Object with the following format:
```
{
  "slot_duration_minutes": 30,
  "slots": [
      "2024-03-18T09:30:00",
      "2024-03-18T10:00:00"
    ]
}
```
The API can be queried by specifying a query string with the arguments:
- `third_party_callback=True` - Indicates that the callback is for a third party and thus capacity restrictions should not apply, defaults to `False`
- `num_days=n` - The number of days to return, n can be a value between 1 and 31, defaults to 7.

> [!IMPORTANT]  
> This API includes previous logic such as non-working days, these rules can not be overwritten by a CSV upload.
> This allows `cla_public` to remove this business logic and act as a presentation layer.
 
## Any other changes that would benefit highlighting?

Intentionally left blank.

## Checklist

- [x] Provided JIRA ticket number in the title, e.g. "LGA-152: Sample title"

[LGA-3003]: https://dsdmoj.atlassian.net/browse/LGA-3003?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

### CODE REVIEW

**Review by TawneeOwl — APPROVED** [review]
LGTM 🚀

**Review by said-moj — APPROVED** [review]

**Review by said-moj — DISMISSED** [review]

**Review by TawneeOwl — APPROVED** [review]
LGTM

**Review by TawneeOwl — DISMISSED** [review]
LGTM :shipit:

**Review by said-moj — DISMISSED** [review]

**Review by said-moj — DISMISSED** [review]

**Comment by said-moj** [comment]
I get the following error when trying to run migrations on a fresh db
`django.db.utils.ProgrammingError: column "callback_type" of relation "legalaid_case" does not exist`

**Review by said-moj — DISMISSED** [review]

**Review by Pheonnexx — APPROVED** [review]

**Review by TawneeOwl — APPROVED** [review]
LGTM :shipit:

**Pull request merged**
