### PR TITLE
LGA-2787 Removing old Gov Notify code and enviroment varibles

### PR DESCRIPTION
**Pull request by psweeting1**
## What does this pull request do?

Removed old Gov notify code and references to old and unused environment variables.

## Checklist

[LGA-2787](https://dsdmoj.atlassian.net/browse/LGA-2787)

[LGA-2787]: https://dsdmoj.atlassian.net/browse/LGA-2787?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

### CODE REVIEW

**Review by Pheonnexx — DISMISSED** [review]
LGTM :shipit:

**Review by said-moj — APPROVED** [review]
👍 LGTM

**Review by Pheonnexx — APPROVED** [review]
LGTM

**Review by TawneeOwl — APPROVED** [review]
LGTM 🚢

**Pull request merged**
