### PR TITLE
Bug/lga 2458 cla backend incorrect email address being sent

### PR DESCRIPTION
**Pull request by TawneeOwl**
## What does this pull request do?

Fixes the stuart monroe email being sent viathe notify service.

## Any other changes that would benefit highlighting?

Intentionally left blank.

## Checklist

- [ ] https://dsdmoj.atlassian.net/jira/software/c/projects/LGA/boards/226?modal=detail&selectedIssue=LGA-2458
- [ ] Removed the notify code that sends an email on callback
- [ ] Removed the tests in relation to the notify callback

### CODE REVIEW

**Comment by said-moj** [comment]
You can also remove the setting details in `settings.GOVUK_NOTIFY_TEMPLATES["CALLBACK_CREATED_PERSONAL"]`

**Review by psweeting1 — APPROVED** [review]
LGTM

**Review by MishNajam — APPROVED** [review]
LGTM

**Review by said-moj — DISMISSED** [review]
👍 LGTM

**Review by Pheonnexx — APPROVED** [review]
LGTM

**Review by jogilder — APPROVED** [review]
LGTM

**Review by psweeting1 — APPROVED** [review]
LGTM

**Pull request merged**
