### PR TITLE
LGA-2302 - Add additional 'Foster carer or potential adoptive parent' category

### PR DESCRIPTION
**Pull request by said-moj**
## What does this pull request do?

- Add additional 'Foster carer or potential adoptive parent' category
- Skip the means checking for this new catgeory 

## Any other changes that would benefit highlighting?

Adding the following to the nodes context makes sure that means test is skipped
```
<context xmlns="" xml:space="preserve">
<finance xml:space="preserve">passported</finance>
</context>
```

## Checklist

- [ ] Provided JIRA ticket number in the title, e.g. "LGA-152: Sample title"

### CODE REVIEW

**Review by psweeting1 — DISMISSED** [review]
LGTM

**Review by Pheonnexx — APPROVED** [review]
LGTM 🚀

**Review by Pheonnexx — APPROVED** [review]
LGTM

**Review by jogilder — APPROVED** [review]
LGTM

**Pull request merged**
