### PR TITLE
LGA-1500 Add guidance notes fixture as part of data to be loaded into DB

### PR DESCRIPTION
**Pull request by mayowaadeniyi**
## What does this pull request do?

- Adds guidance notes fixture `initial_guidance_notes.json` as part of data to be loaded into DB
- Updated README to reflect this change (will require us to run `./manage loaddata initial_guidance_notes.json` command to apply the change)

## Checklist

- [x] Provided JIRA ticket number in the title, e.g. "LGA-152: Sample title"

### CODE REVIEW

**Review by exonian — COMMENTED** [review]
Looks good.
The clue to what app.json is for is in line 10. I think you're right to update it.


> will require us to rerun the ./manage loaddata -fixtures- command to apply the change)

Could you just clarify exactly what that command is going to look like, please? `-fixtures-` is ambiguous, and I want to be sure we're on the same page

**Comment by mayowaadeniyi** [comment]
> Looks good.
> The clue to what app.json is for is in line 10. I think you're right to update it.
> 
> > will require us to rerun the ./manage loaddata -fixtures- command to apply the change)
> 
> Could you just clarify exactly what that command is going to look like, please? `-fixtures-` is ambiguous, and I want to be sure we're on the same page

Full command will look like this (like how it does in README with my changes):

> ./manage.py loaddata initial_groups.json kb_from_knowledgebase.json initial_category.json test_provider.json test_provider_allocations.json initial_mattertype.json test_auth_clients.json initial_media_codes.json test_rotas.json initial_guidance_notes.json

And ah ok. When we move to Kubernetes fully, will we still need this? I thought all our hosting was done on Kubernetes, plus this exact command is run in `create_db.sh`

**Comment by exonian** [comment]
> Full command will look like below (like how it does in README with my changes):

Do you need to run all of that? Is it desirable to? Does it matter?

**Comment by exonian** [comment]
> And ah ok. When we move to Kubernetes fully, will we still need this? I thought all our hosting was done on Kubernetes, plus this exact command is run in create_db.sh

I have no idea what the "this" in "will we still need this" is

**Comment by mayowaadeniyi** [comment]
> Do you need to run all of that? Is it desirable to? Does it matter?

No I just mentioned it, just so we are aware

> I have no idea what the "this" in "will we still need this" is

So my question was we will still need the `app.json` file? Are we still using heroku as part of our app?

**Comment by exonian** [comment]
> No I just mentioned it just so we know

So what do you propose that we _do_ run?

> So my question was we will still need the app.json file? Are we still using heroku as part of our app?

We don't use heroku at all for template deploy or kubernetes, no.

**Comment by mayowaadeniyi** [comment]
> So what do you propose that we _do_ run?

After having a little think about it, we will just need to run ./manage loaddata initial_guidance_notes.json as this is the only data that is not in the DB (everything else is)
> We don't use heroku at all for template deploy or kubernetes, no.

To be honest deciding whether to delete `app.json` feels out of scope for this ticket anyway, so I think nvm

**Comment by exonian** [comment]
Super. I agree on both counts. If you update the description to reflect both those things, I'll approve it 👍

**Pull request merged**
