### PR TITLE
Release "develop" branch, 13th September

### PR DESCRIPTION
**Pull request by sldblog**
## What does this pull request do?

Releases:

- #470 (Build unit tests and Docker image in CircleCI)
- #472 (Add code owners and pull request templates)
- #473 (Push to both DSD and ECR Docker registries)
- #475 (Release process)

## Any other changes that would benefit highlighting?

🚨 We will be changing the default branch to `master` once this pull request is deployed.

- Added wait script before executing `psql` commands to ensure the database is operational before running commands on it.
- Check that dependencies were successfully installed with `pip check`. It turns out they were not. 😱 
    - **Reverted** this check. Unfortunately, `django-moj-irat` has a dependency for `django >= 1.8` which this project cannot satisfy. The dependency tree is broken. 😱 😱

### CODE REVIEW

**Comment by rowlando** [comment]
Good to go. Just to note, the only production code change is in `cla_backend/apps/reports/utils.py`.

**Comment by sldblog** [comment]
It looks like we could improve the test stability by adding a wait-for-database step.
I'll try and cook up something on that.

**Comment by rowlando** [comment]
> It looks like we could improve the test stability by adding a wait-for-database step.
> I'll try and cook up something on that.

Are you going to do this?

**Comment by sldblog** [comment]
Yes, I did it in 57f4f74c98782adb0c10baa0824dd44083781962. Forgot to update on this, sorry.

**Pull request merged**
