### PR TITLE
Flick dependant apps in out of maintenance mode

### PR DESCRIPTION
**Pull request by said-moj**
## What does this pull request do?

Puts cla_frontend and cla_public in and out of maintenance mode when putting cla_backend into maintenance mode

## Any other changes that would benefit highlighting?

Intentionally left blank.

## Checklist

- [ ] Provided JIRA ticket number in the title, e.g. "LGA-152: Sample title"

### CODE REVIEW

**Review by jogilder — APPROVED** [review]
LGTM

**Review by MishNajam — DISMISSED** [review]
LGTM ✅

**Review by jogilder — APPROVED** [review]
LGTM

**Review by MishNajam — APPROVED** [review]
✅

**Pull request merged**
