### PR TITLE
LGA-2313 Enabling Modsecurity in detection mode for cla_backend

### PR DESCRIPTION
**Pull request by psweeting1**
Removing snippet and putting ModSecurity into dection mode only.

## What does this pull request do?

Required.

## Any other changes that would benefit highlighting?

[Kibana](https://kibana.cloud-platform.service.justice.gov.uk/_plugin/kibana/goto/ae8948f736fbcbf6346bd118dccbf8a3)

## Checklist

[LGA-2313](https://dsdmoj.atlassian.net/browse/LGA-2313)

[LGA-2313]: https://dsdmoj.atlassian.net/browse/LGA-2313?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

### CODE REVIEW

**Review by Pheonnexx — APPROVED** [review]

**Comment by said-moj** [comment]
What do you think of renaming this PR as it's not enabling modsec but removing SecRuleRemoveById 200001?

**Review by said-moj — APPROVED** [review]
👍 LGTM

**Review by Pheonnexx — APPROVED** [review]
LGTM

**Review by MishNajam — APPROVED** [review]
LGTM

**Pull request merged**
